/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import { Provider } from '@ethersproject/providers'
import type {
  IChainRunnersRenderer,
  IChainRunnersRendererInterface,
} from '../IChainRunnersRenderer'

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
      {
        components: [
          {
            internalType: 'uint256',
            name: 'dna',
            type: 'uint256',
          },
        ],
        internalType: 'struct ChainRunnersTypes.ChainRunner',
        name: 'runnerData',
        type: 'tuple',
      },
    ],
    name: 'tokenURI',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]

export class IChainRunnersRenderer__factory {
  static readonly abi = _abi
  static createInterface(): IChainRunnersRendererInterface {
    return new utils.Interface(_abi) as IChainRunnersRendererInterface
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): IChainRunnersRenderer {
    return new Contract(address, _abi, signerOrProvider) as IChainRunnersRenderer
  }
}
